BankApp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('index', views.index, name='index'),
    path('',views.home,name='home'),
    path("register", views.register, name="register"),
    path("Requester", views.Requester, name="Requester"),
    path("RequesterBloodIsAvailable", views.RequesterBloodIsAvailable, name="RequesterBloodIsAvailable"),
    path("Donner", views.Donner, name="Donner"),
    path("BankAdminPage", views.BankAdminPage, name="BankAdminPage"),
    path("BankAdminPageHistory", views.BankAdminPageHistory, name='BankAdminPageHistory'),
    path("is_donner_already_donated", views.is_donner_already_donated, name="is_donner_already_donated"), 
    path("send_promotional_email/<int:value>/",views.send_promotional_email, name = "send_promotional_email"),
]

CovidPlazmaBank/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('BankApp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)

BankApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Banks(models.Model):
    Bcity = models.CharField(max_length=100)
    BState = models.CharField(max_length=100)
    def __str__(self):
        return self.Bcity

class DonnerModel(models.Model):
    fullname = models.CharField(max_length=100)
    Did = models.ForeignKey(User, on_delete=models.CASCADE)
    phone_no = models.IntegerField()
    BloodGrp = models.CharField(max_length=20)
    Age = models.IntegerField()
    is_diabitic =  models.BooleanField()
    Bid = models.ForeignKey(Banks, on_delete=models.CASCADE)    
    donnate_date = models.DateField()
    is_recived_by_bank = models.BooleanField(default=False)
    Secret = models.CharField(max_length=100,default="SGN1ONS")    
    
    def __str__(self):
        return self.fullname
    
    
class Blood(models.Model):
    Did = models.ForeignKey(User, on_delete=models.CASCADE)    
    Bid = models.ForeignKey(Banks, on_delete=models.CASCADE)  
    BloodGrp = models.CharField(max_length=20) 
    Secret = models.CharField(max_length=100)    
    is_available = models.BooleanField(default=True)     
    
class RequesterModel(models.Model):
    fullname = models.CharField(max_length=100)
    Rid = models.ForeignKey(User, on_delete=models.CASCADE)
    phone_no = models.IntegerField()
    BloodGrp = models.CharField(max_length=20)
    Age = models.IntegerField()
    is_diabitic =  models.BooleanField()
    def __str__(self):
        return self.fullname

class RequestNoBlood(models.Model):
    RNid = models.ForeignKey(User, on_delete=models.CASCADE)


class RequestedBlood(models.Model):
    Rqid = models.ForeignKey(User, on_delete=models.CASCADE)
    Dnid = models.IntegerField()     
    Bid = models.ForeignKey(Banks, on_delete=models.CASCADE)   
    Bloodid = models.ForeignKey(Blood, on_delete=models.CASCADE)
    Secret = models.CharField(max_length=100) 

templates/BankAdmin.html
{% extends "base.html" %}

{% block content %} 
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
<h4 class="text-center mt-5 mb-5"> 
	History of Donner 
</h4>
{% if request.user.is_staff%}
<table class="table table-stripped container ">
	
  <tr >
    <th>Name</th>
    <th>Phone No</th>
    <th>Blood Grp</th>
	<th>Age</th>
	
	<th>Is_diabetic</th>
	{% if is_history %}
		<th>Secret </th>
	{%endif%}	
	<th>Recevied</th>
	{% if is_history %}
		<th></th>	
	{%endif%}	
  </tr>
  
  <p class="text-danger">
	{{Perror}}
  </p>
  
  {% for i in DonnerData %}
	  <form method="POST">
	  {% csrf_token %}
	  <input type="hidden" name="id1" value="{{i.id}}">
	  <input type="hidden" name="fullname" value="{{i.fullname}}">
	  <input type="hidden" name="Did" value="{{i.Did_id}}">  
	<tr>	
		<td>{{i.fullname}}</td>
		<td>{{i.phone_no}}</td>
		<td>{{i.BloodGrp}}</td>
		<td>{{i.Age}}</td>
		<td>
		{% if i.is_diabitic %}
			<span class="text-warning"><b>Yes</b></span>
		{%else%}
		No
		{%endif%}	
		
		</td>
		{% if is_history %}
		<td>
			<input type="text" name="Secret" placeholder="Secret">
		</td>
		{%endif%}
		<td>

		{% if i.is_recived_by_bank %}
		<span class="text-success">	<b>Yes</b></span>
		{%else%}
		<span class="text-danger">No</span>
		{%endif%}	

		</td>
		{% if is_history %}
		<td>
			<input type="submit" name="login" value="Recevied">
		</td>
		{%endif%}
		</form>
		
	</tr>
	{%endfor%}
</table>

{%else%}

<h1> You are not authorize to see this page.</h1>


{%endif%}
{% endblock %}

templates/BankHistory.html
{% extends "base.html" %}
{% load static %}
{% block content %} 
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>


<div class="container mb-5">
	<h4 class="text-center mt-5 mb-5"> 
		History of Donner 
	</h4>
	<div class="row">
	
	  <div class="col-4 align-self-start ">
		<img src="{% static '3961373-removebg-preview.png' %}" class="w-100 mt-5"alt="My image">
	  </div>
	  <div class="col-8 align-self-center">
		
		{% if request.user.is_staff%}
		<table class="table table-stripped container ">
			
		  <tr >
			<th>Name</th>
			<th>Phone No</th>
			<th>Blood Grp</th>
			<th>Age</th>
			
			<th>Is_diabetic</th>
			{% if is_history %}
				<th>Secret </th>
			{%endif%}	
			<th>Recevied</th>
			{% if is_history %}
				<th></th>	
			{%endif%}	
		
			<th>  Promotion </th>
		  </tr>
		  
		  <p class="text-danger">
			{{Perror}}
		  </p>
		  
		  {% for i in DonnerData %}
			  <form method="POST">
			  {% csrf_token %}
			  <input type="hidden" name="id1" value="{{i.id}}">
			  <input type="hidden" name="fullname" value="{{i.fullname}}">
			  <input type="hidden" name="Did" value="{{i.Did_id}}">  
			<tr>	
				<td>{{i.fullname}}</td>
				<td>{{i.phone_no}}</td>
				<td>{{i.BloodGrp}}</td>
				<td>{{i.Age}}</td>
				<td>
				{% if i.is_diabitic %}
					<span class="text-warning"><b>Yes</b></span>
				{%else%}
				No
				{%endif%}	
				
				</td>
				{% if is_history %}
				<td>
					<input type="text" name="Secret" placeholder="Secret">
				</td>
				{%endif%}
				<td>
		
				{% if i.is_recived_by_bank %}
				<span class="text-success">	<b>Yes</b></span>
				{%else%}
				<span class="text-danger">No</span>
				{%endif%}	
		
				</td>
				{% if is_history %}
				<td>
					<input type="submit" name="login" value="Recevied">
				</td>
				{%endif%}
				<td> 
					<a href="/send_promotional_email/{{i.id}}" >Send</a>
				</td>
				</form>
				
			</tr>
			{%endfor%}
		</table>
		
	  </div>
	
	</div>
  </div>
{%else%}

<h1> You are not authorize to see this page.</h1>


{%endif%}
{% endblock %}

templates/Donner.html
{% extends "base.html" %}

{% block content %} 

<div class="container mt-5">
	{%if errormessage %}
	<h4 class="text-danger text-center ">{{errormessage}}</h4>
	{%endif%}<form method="POST">
		{% csrf_token %}
<div class="card border-success mb-3 col-12 mt-5">
	<div class="card-header bg-transparent border-success">Donate Blood</div>
	<div class="card-body text-dark">
		{%if Emess%}
		<div class="row">
			<p> {{Emess}}</p>
		</div>
		{%endif%}	
		<input type="text" class="form-control mt-3 mb-4" placeholder="Pleace Enter Your Full Name" name="fullname" maxlength="50" required id="id_fullname">
		<input type="hidden"  class="form-control mt-3 mb-4" value="{{request.user.id}}" name="Did" required id="id_Did">
		
		<input type="number"  class="form-control mt-3 mb-4" placeholder="Pleace Enter Your Contact Number" pattern="\d{10}" name="phone_no" maxlength="10" required id="id_phone_no">
		<label for="id_is_diabitic"  class=" ml-2 ">Is diabitic:</label>
		<input type="checkbox"   name="is_diabitic" id="id_is_diabitic" class="mt-1 mb-4">
		<select name="BloodGrp"  class="form-control" required id="id_BloodGrp">
			<option value="" selected>Please Select Your Blood Group</option>
			<option value="A+">A+</option>
			<option value="A-">A-</option>
			<option value="B+">B+</option>
			<option value="B-">B-</option>
			<option value="O+">O+</option>
			<option value="O-">O-</option>
			<option value="AB+">AB+</option>
			<option value="AB-">AB-</option>
		</select>
		
		<input type="number"  class="form-control mt-4 mb-4" placeholder="Pleace Enter Your Age" name="Age" required id="id_Age">
		<select name="Bid"  class="form-control" required id="id_Bid">
			<option value="" selected>Please Select Blood Bank Location</option>
		{% for i in Blist %}
			<option value={{i.0}}>{{i.1}}</option>
		{% endfor %}
		</select>
		<input type="date"  class="form-control mt-4 mb-4" placeholder="date" name="donnate_date" required id="id_donnate_date">
		<input type="hidden"  name="Secret" value="{{SecVal}}">
	

	</div>
	<div class="card-footer bg-transparent border-success">	<input type="submit"class="form-control mt-4 mb-4 btn btn-primary" name="login" value="Request"></div>
  </div>

</div>
{% endblock %}

templates/Donner_already.html
{% extends "base.html" %}
{% load static %}
{% block content %} 


<!--Donner  	--> 





<div class="clearfix container mt-4 mb-5">
	<h1>Donate Blood</h1>
	<div class="row">
	<div class="logname col-6">
		
		<img src="{% static '2867045-removebg-preview.png' %}" class="w-100 float-md-end " alt="Blood donation">
		
	</div>

	<div class="col-5 mt-5">
		<form method="POST">
			{% csrf_token %}
			<div class="loginfrm mt-5">
				
	
				<div class="row">
					<p>Please choose Date on or after : {{Ddate}}</p>
				</div>
	
				{% if text %}
				<div class="row">
					<p>{{text}} {{Ddate}}</p>
				</div>
				{%endif%}
	
				<input type="hidden" value="{{request.user.id}}" name="id1" >
				<div class="row">
				</br>
					<p>Choose Date for Donate : </p>
					<input type="date" class="form-control" name="DonnerData">	
				</div>
						
				<div class="row mt-5">
					<input type="submit" class="btn btn-primary" name="login" value="Request">
				</div>
			</div>
		</form>
	</div>
  </div>
</div>
{% endblock %}

templates/Requester.html
{% extends "base.html" %}

{% block content %} 


<!--Requester--> 
<div class="container py-5">
	<form method="POST">
		{% csrf_token %}	
			<div class="loginfrm">
			<div class="logname">
				<h1>Donate Blood</h1>
			</div>
			<div class="row">
				<tr>
					<td>
						<input type="text" placeholder="Fullname" name="fullname" maxlength="100" required id="id_fullname">
					</td>
				</tr>
				</div>
								<input type="hidden" value="{{request.user.id}}" name="Rid" required id="id_Rid">
				<div class="row">
				<tr>
					<td>
						<input type="number" placeholder="Contact Number" name="phone_no" required id="id_phone_no">
					</td>
				</tr>
				</div>
				<div class="row">
					<tr>
					<th>
						<label for="id_is_diabitic">Is diabitic:</label>
						<input type="checkbox" name="is_diabitic" id="id_is_diabitic">
					</td>
					</tr>			
				</div>
				<div class="row">
				<tr>
					<td>
						<select name="BloodGrp" required id="id_BloodGrp">
							<option value="" selected>Blood Group</option>

							<option value="A+">A+</option>
						
							<option value="A-">A-</option>
						
							<option value="B+">B+</option>
							
							<option value="B-">B-</option>
							
							<option value="O+">O+</option>
							
							<option value="O-">O-</option>
							
							<option value="AB+">AB+</option>
							
							<option value="AB-">AB-</option>
							
						</select>
						
					</td>
				</tr>
				</div>
				<div class="row">
				<tr>
					<td>
						<input type="number" placeholder="Enter your Age" name="Age" required id="id_Age">
					</td>
				</tr>
				</div>
				<div class="row">
				<tr>
					<td>
						<input type="text" placeholder="City" name="city" maxlength="50" required id="id_city">
					</td>
				</tr>
				</div>
				<div class="row">
				<tr>
					<td>
						<input type="text" placeholder="State" name="state" maxlength="50" required id="id_state">
					</td>
				</tr>
				</div>
				<div class="row">
				<input type="submit" name="login" value="Request">
				</div>


				
		</div>
		</div>
	</form>
	
</div>


{% endblock %}

templates/RequesterForBlood.html
{% extends "base.html" %}

{% block content %} 


{% if is_show %}
    <div>
        <form method="POST" action="{% url 'RequesterBloodIsAvailable' %}">
            {% csrf_token %}
            <p>Blood Group : </p>
            <input type="text" name="BloodGrp" value="{{ BloodGrp }}">
            <p> Request For the Blood Group {{BloodGrp}} </p>
            <button class="btn btn-primary" type="submit">Request</button>
        </form>

    </div>
{% endif %}

{% if is_data %}

        <h3>for {{DonnerData.0}} Blood Grp </h3>
        <h4> you have to go to {{DonnerData.1}},{{DonnerData.2}}</h2>
{% endif %}

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>{% block title %}Cloud Based Blood Bank System{% endblock %}</title>
<link rel="shortcut icon" type="image/png" href="{% static 'image/favicon.ico' %}"/>
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet"> 
<link href="{% static 'js/bootstrap.min.js' %}" rel="stylesheet">
<link href="{% static 'js/jquery.min.js' %}" rel="stylesheet">
<link href="{% static 'js/popper.min.js' %}" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<style type="text/css">
  .card-header{z-index: 1000}
/*  .bgimage
{
	background:url( "{% static 'images/1.jpg' %}");
	background-size:cover;	
	height: 950px;
    opacity: 0.7;
}*/
.auth-one-bg-position {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    width: 100%;
    height: 380px;
}

.auth-one-bg {
   background-position: center;
    background-size: cover;
    background-image: radial-gradient(rgba(0, 0, 0, 0) 0%, rgb(25 75 255 / 17%) 100%), radial-gradient(rgba(0, 0, 0, 0) 33%, rgb(9 87 255 / 47%) 166%);
}

#video-container {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: -1;
}

#video-container video {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    object-fit: cover;
}

.auth-one-bg .bg-overlay {
    background: linear-gradient(to right, rgb(99 41 255 / 6%), rgb(120 247 40 / 18%));
    opacity: 0.9;
}

.bg-overlay {
    position: absolute;
    height: 100%;
    width: 100%;
    right: 0;
    bottom: 0;
    left: 0;
    top: 0;
    opacity: 0.7;
    background-color: #000;
}

.auth-one-bg .shape {
    position: absolute;
    bottom: 0;
    right: 0;
    left: 0;
    z-index: 1;
    pointer-events: none;
}

.auth-one-bg .shape > svg {
    width: 100%;
    height: auto;
    fill: #ecf0fa;
}

.particles-js-canvas-el {
    position: relative;
}

.auth-page-wrapper .auth-page-content {
    padding-bottom: 60px;
    position: relative;
    z-index: 2;
    width: 100%;
}

.login-bg {
    background-color: rgb(255 255 255 / 50%);
    backdrop-filter: saturate(180%) blur(7px);
    border: 2px solid rgb(255 255 255 / 70%);
    box-shadow: rgb(0 0 0 / 10%) 0px 10px 15px -3px, rgb(0 0 0 / 5%) 0px 4px 6px -2px;
}


.form-label {
    font-size: 17px;
    font-family: calibri;
}

body {
    background: #ecf0fa !important;
}

.row
{
	border:0px solid;
	height:40px;
	margin-top:20px;
	padding:10px;
}

/* Set global styles */
* {
  box-sizing: border-box;
  font-family: Arial, sans-serif;
}

body {
  margin: 0;
}

header {
  background-color: #f44336;
  color: white;
  padding: 20px;
}

nav ul {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  justify-content: space-between;
}

nav li {
  margin: 0 10px;
}

nav a {
  color: white;
  text-decoration: none;
  font-weight: bold;
  text-transform: uppercase;
}

main {
  padding: 20px;
}

section {
  margin-bottom: 40px;
}

h1, h2 {
  text-align: center;
}

button {
  background-color: #f44336;
  color: white;
  border: none;
  padding: 10px 20px;
  border-radius: 5px;
  cursor: pointer;
}

button:hover {
  background-color: #f28d81;
}

ul {
  list-style: disc;
  margin-left: 20px;
}

footer {
  background-color: #f2f2f2;
  padding: 20px;
  text-align: center;
  font-size: 0.8em;
}

/* Media queries for responsive design */
@media only screen and (max-width: 768px) {
  nav ul {
    flex-direction: column;
  }

  nav li {
    margin: 10px 0;
  }
}


</style>

</head>
<body>
<div>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<a class="navbar-brand text-danger" href="#">Cloud Based Blood Bank System</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
	  
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		  <ul class="navbar-nav mr-auto">
			
		  </ul>
		  <form class="form-inline my-2 my-lg-0">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
				  <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
				{% if user.is_authenticated %}
				<a href="{% url 'home' %}" class="nav-link text-success">  <b>Hiii {{ user.username }}!</b></a>
				</li> 
				
					 {% if request.user.is_staff%}	
                        <li class="nav-item ">
						 <a href="{% url 'BankAdminPage' %}" class="nav-link "> <b>&nbsp;&nbsp;Admin </b></a>
						</li>
                        <li class="nav-item "></li>
						 <a href="{% url 'BankAdminPageHistory' %}" class="nav-link "> <b>&nbsp;&nbsp;History </b></a>
						</li>          
					 {%else%}	
					 <li class="nav-item ">
						 <a href="{% url 'Donner' %}" class="nav-link "> <b>Donate</b>  </a>
		            </li>
					 {%endif%}	
					 <a href="{% url 'logout' %}" class="nav-link "> <b>&nbsp;&nbsp;Log Out </b></a> 
				 {% else%}
				 <a href="{% url 'login' %}" class="nav-link "> <b>&nbsp;&nbsp;Log In </b></a>
				 {% endif %}
				</li>
		  </form>
		</div>
	  </nav>
    
</div>
{% block content %}

{% endblock %}

<!-- Footer -->

<footer class="page-footer font-small blue fixed-bottom">
    <!-- Copyright -->
     <div class="card-footer bg-light text-center text-muted">
        © 2023 Copyright:
    <a href="" class="text-danger">Cloud Based Blood Bank System</a>
    </div>
 

  <!-- Copyright -->
</footer>
<!-- Footer -->
</body>
</html>

templates/home.html

{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}


<div class="bgimage">
    <div class="row justify-content-center">
        <div class="col-4">
            <section id="about" class="align-self-center">
                <img src="{% static 'Blood donation-pana.png' %}" class="w-100 "alt="Blood donation">
              
            </section>
            
        </div>
        <div class="col-4 mt-5">
            <section id="benefits" class="mt-5">
                
              <h2>About the Cloud Based Blood Bank System</h2>
              <p>Our mission is to connect donors with those in need and make the blood donation process as seamless as possible. </p>
                <h2>Benefits of Donating Blood</h2>
                <ul>
                  <li>Helps save lives</li>
                  <li>Improves your own health by reducing risk of heart disease and cancer</li>
                  <li>Free health checkup including blood pressure, hemoglobin, and infectious diseases testing</li>
                </ul>
              </section>
        </div>
      </div>


</div>
<h1>{{text}} </b>{{Ddate}}</b></h1>

{%if SecVal %}
<h1> please save this Secret : <b> {{SecVal}} </b> </h1>

{% endif%}
{% endblock %}

templates/home2.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}


<div class="bgimage">


</div>
<h1>{{text}} </b>{{Ddate}}</b></h1>

{%if SecVal %}
<h1> please save this Secret : <b> {{SecVal}} </b> </h1>

{% endif%}
{% endblock %}

templates/new_1.html
		<div class="loginfrm">
			<div class="logname">
				<h1>Donate Blood</h1>
			</div>
			<div class="row">
				<tr>
					<td>
						<input type="text" placeholder="Fullname" name="fullname" maxlength="100" required id="id_fullname">
					</td>
				</tr>
				</div>
								<input type="hidden" value="{{request.user.id}}" name="Did" required id="id_Did">
				<div class="row">
				<tr>
					<td>
						<input type="number" placeholder="Contact Number" name="phone_no" required id="id_phone_no">
					</td>
				</tr>
				</div>
				<div class="row">
					<tr>
					<th>
						<label for="id_is_diabitic">Is diabitic:</label></th><td><input type="checkbox" name="is_diabitic" id="id_is_diabitic">
					</td>
					</tr>			
				</div>
				<div class="row">
				<tr>
					<td>
						<input type="text" placeholder="Blood group:" name="BloodGrp" maxlength="20" required id="id_BloodGrp">
					</td>
				</tr>
				</div>
				<div class="row">
				<tr>
					<td>
						<input type="number" placeholder="Enter your Age" name="Age" required id="id_Age">
					</td>
				</tr>
				</div>
				<div class="row">
				<tr>
					<td>
						<input type="text" placeholder="City" name="city" maxlength="50" required id="id_city">
					</td>
				</tr>
				</div>
				<div class="row">
				<tr>
					<td>
						<input type="text" placeholder="State" name="state" maxlength="50" required id="id_state">
					</td>
				</tr>
				</div>
				<div class="row">
				<tr>
					<th>
						<label for="id_Bid">Bid:</label>
					</th>
					<td>
						<select name="Bid" required id="id_Bid">
							<option value="" selected>---------</option>

							<option value="1">Banks object (1)</option>
						
							<option value="2">Banks object (2)</option>
						
							<option value="3">Banks object (3)</option>
						</select>
					</td>
				</tr>
				</div>
				<br/><br/>